/** Pure username helpers (normalisation, validation, suggestion, generated-name detection). */

export const USERNAME_MIN = 3;
export const USERNAME_MAX = 30;
const USERNAME_REGEX = /^[a-z0-9_]{3,30}$/;
const ALLOWED_CHARS_REGEX = /^[a-z0-9_]*$/;
const GENERATED_USERNAME_REGEX = /^user_[0-9a-f]{12}$/;

/** True when the username is the placeholder generated by the DB trigger. */
export function isGeneratedUsername(username: string): boolean {
  return GENERATED_USERNAME_REGEX.test(username);
}

/** Applied on every keystroke: lowercase and remove whitespace. Other characters are kept. */
export function normalizeUsernameInput(text: string): string {
  return text.toLowerCase().replace(/\s/g, '');
}

export type UsernameValidation =
  | { status: 'idle' }
  | { status: 'invalid'; message: string }
  | { status: 'ok' };

export function validateUsername(value: string): UsernameValidation {
  if (value.length === 0) return { status: 'idle' };
  if (!ALLOWED_CHARS_REGEX.test(value)) {
    return { status: 'invalid', message: 'Use only letters, numbers and underscores.' };
  }
  if (value.length < USERNAME_MIN) {
    return { status: 'invalid', message: 'Use at least 3 characters.' };
  }
  if (!USERNAME_REGEX.test(value)) {
    return { status: 'invalid', message: 'Use at most 30 characters.' };
  }
  if (value.startsWith('user_')) {
    return { status: 'invalid', message: "Usernames can't start with \"user_\"." };
  }
  return { status: 'ok' };
}

/** Slug of a display name, or '' if the result is unusable. */
export function suggestUsername(displayName: string | null | undefined): string {
  const slug = (displayName ?? '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/đ/g, 'd')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, USERNAME_MAX)
    .replace(/_+$/g, '');
  if (slug.length < USERNAME_MIN || slug.startsWith('user_')) return '';
  return slug;
}
