-- =============================================================================
-- 0002_save_trip_stops.sql : atomic replace of a trip's stops + stop photos
--
-- HOW TO APPLY
--   Supabase Dashboard -> SQL Editor -> New query -> paste this whole file -> Run.
--   Run it ONCE (not idempotent: a second run fails on "already exists" and the
--   transaction rolls back). Requires 0001_init.sql to be applied first.
--   Afterwards regenerate types:  npm run gen:types
--   Dev-only rollback: 0002_save_trip_stops.down.sql
--
-- save_trip_stops(p_trip_id, p_stops) makes the stops/photos of a trip EXACTLY
-- equal to p_stops, in one transaction (create-publish, retry and edit all use it):
--   p_stops = [ { "id": uuid, "name": text, "lat": num, "lng": num,
--                 "address": text|null, "notes": text|null,
--                 "photos": [ { "id": uuid, "storage_path": text }, ... ] }, ... ]
--   * array order = position (0..n-1); photo array order = photo position.
--   * ids are generated by the client (crypto uuid), so retrying is idempotent.
--   * stops of the trip not in the payload are deleted (photos cascade);
--     photos of kept stops not in the payload are deleted; the rest are
--     updated; unknown ids are inserted.
--   * returns the storage_path of every photo row that no longer exists, so the
--     client can delete those Storage files AFTER this call succeeded.
-- SECURITY INVOKER: RLS and the 20-stop / 5-photo triggers of 0001 still apply.
-- Plain upsert (ON CONFLICT) is deliberately NOT used: the BEFORE INSERT limit
-- triggers fire on the insert attempt and would reject updates of a full trip.
-- =============================================================================

begin;

create function public.save_trip_stops(p_trip_id uuid, p_stops jsonb)
returns text[] language plpgsql security invoker set search_path = '' as $$
declare
  v_uid         uuid := (select auth.uid());
  v_prefix      text := (select auth.uid())::text || '/' || p_trip_id::text || '/';
  v_path_re     text := '^' || v_prefix || '[A-Za-z0-9_-]{1,64}\.(jpg|jpeg|png|webp)$';
  v_stop        jsonb;
  v_photo       jsonb;
  v_photos      jsonb;
  v_stop_id     uuid;
  v_stop_ids    uuid[] := '{}';
  v_photo_ids   uuid[] := '{}';
  v_photo_stops uuid[] := '{}';
  v_photo_pos   int[]  := '{}';
  v_photo_paths text[] := '{}';
  v_pos         int;
  v_path        text;
  v_removed     text[];
begin
  -- owner check + serialise concurrent saves of the same trip
  perform 1 from public.trips t
    where t.id = p_trip_id and t.owner_id = v_uid for update;
  if not found then raise exception 'trip not found or not owner' using errcode = '42501'; end if;

  -- ---- validate the payload (cheap, before touching any row) ----
  if p_stops is null or jsonb_typeof(p_stops) <> 'array' then
    raise exception 'stops must be a json array' using errcode = '22023';
  end if;
  if octet_length(p_stops::text) > 524288 then
    raise exception 'payload too large' using errcode = '22023';
  end if;
  if jsonb_array_length(p_stops) > 20 then
    raise exception 'stop limit reached' using errcode = 'P0001';
  end if;

  for v_stop in select e.value from jsonb_array_elements(p_stops) as e loop
    if jsonb_typeof(v_stop) <> 'object' or (v_stop ->> 'id') is null then
      raise exception 'every stop needs an id' using errcode = '22023';
    end if;
    v_stop_id  := (v_stop ->> 'id')::uuid;
    v_stop_ids := v_stop_ids || v_stop_id;

    v_photos := coalesce(v_stop -> 'photos', '[]'::jsonb);
    if jsonb_typeof(v_photos) <> 'array' then
      raise exception 'photos must be a json array' using errcode = '22023';
    end if;
    if jsonb_array_length(v_photos) > 5 then
      raise exception 'photo limit reached' using errcode = 'P0001';
    end if;

    v_pos := 0;
    for v_photo in select e.value from jsonb_array_elements(v_photos) as e loop
      v_path := v_photo ->> 'storage_path';
      if (v_photo ->> 'id') is null
         or v_path is null
         or v_path !~ v_path_re then
        raise exception 'invalid photo id or storage_path' using errcode = '22023';
      end if;
      v_photo_ids   := v_photo_ids   || (v_photo ->> 'id')::uuid;
      v_photo_stops := v_photo_stops || v_stop_id;
      v_photo_pos   := v_photo_pos   || v_pos;
      v_photo_paths := v_photo_paths || v_path;
      v_pos := v_pos + 1;
    end loop;
  end loop;

  if (select count(distinct x) from unnest(v_stop_ids) x) <> coalesce(array_length(v_stop_ids, 1), 0)
     or (select count(distinct x) from unnest(v_photo_ids) x) <> coalesce(array_length(v_photo_ids, 1), 0) then
    raise exception 'duplicate stop or photo id' using errcode = '22023';
  end if;

  -- ---- files that will be orphaned (computed BEFORE any delete) ----
  select coalesce(array_agg(sp.storage_path), '{}') into v_removed
    from public.stop_photos sp join public.stops s on s.id = sp.stop_id
    where s.trip_id = p_trip_id and not (sp.storage_path = any(v_photo_paths));

  -- ---- deletes first, so the limit triggers see the final counts ----
  delete from public.stops s
    where s.trip_id = p_trip_id and not (s.id = any(v_stop_ids));

  delete from public.stop_photos sp using public.stops s
    where s.id = sp.stop_id and s.trip_id = p_trip_id
      and not exists (select 1 from unnest(v_photo_ids, v_photo_stops) as u(id, stop_id)
                      where u.id = sp.id and u.stop_id = sp.stop_id);

  -- ---- stops: update kept, insert new (unique positions are deferred) ----
  update public.stops s
    set position = e.ord::int - 1,
        name     = e.v ->> 'name',
        lat      = (e.v ->> 'lat')::double precision,
        lng      = (e.v ->> 'lng')::double precision,
        address  = e.v ->> 'address',
        notes    = e.v ->> 'notes'
    from jsonb_array_elements(p_stops) with ordinality as e(v, ord)
    where s.trip_id = p_trip_id and s.id = (e.v ->> 'id')::uuid;

  insert into public.stops (id, trip_id, position, name, lat, lng, address, notes)
    select (e.v ->> 'id')::uuid, p_trip_id, e.ord::int - 1, e.v ->> 'name',
           (e.v ->> 'lat')::double precision, (e.v ->> 'lng')::double precision,
           e.v ->> 'address', e.v ->> 'notes'
    from jsonb_array_elements(p_stops) with ordinality as e(v, ord)
    where not exists (select 1 from public.stops s
                      where s.id = (e.v ->> 'id')::uuid and s.trip_id = p_trip_id)
    order by e.ord;

  -- ---- photos: update kept, insert new ----
  update public.stop_photos sp
    set position = u.position, storage_path = u.storage_path
    from unnest(v_photo_ids, v_photo_stops, v_photo_pos, v_photo_paths)
         as u(id, stop_id, position, storage_path)
    where sp.id = u.id and sp.stop_id = u.stop_id;

  insert into public.stop_photos (id, stop_id, position, storage_path)
    select u.id, u.stop_id, u.position, u.storage_path
    from unnest(v_photo_ids, v_photo_stops, v_photo_pos, v_photo_paths)
         as u(id, stop_id, position, storage_path)
    where not exists (select 1 from public.stop_photos sp
                      where sp.id = u.id and sp.stop_id = u.stop_id)
    order by u.stop_id, u.position;

  update public.trips set updated_at = now() where id = p_trip_id;

  return v_removed;
end $$;

revoke all on function public.save_trip_stops(uuid, jsonb) from public, anon;
grant execute on function public.save_trip_stops(uuid, jsonb) to authenticated;

commit;
